### ISSUE TITLE
Escaped line breaks in abstract

### ISSUE THREAD

**Issue by stlozhaw** [sustainability-zhaw/extraction-dspace#15]
https://digitalcollection.zhaw.ch/handle/11475/27482
Abstract contains \\\\r\\\\n ? This will mess with the tokenizer in the indexer.

`\\r\\nThe` will be seen as a single word.

By looking at different recent developments of PEDs in Switzerland and Norway, we describe the characteristics of national approaches towards PEDs. By deepening the description of two respective case studies in the two countries, we analyzed how PED approaches are implemented within the specific context. We compare the PED concepts, local implementation and functional issues to analyze the approaches. Our research is based on literature and document analysis and qualitative interviews.\\\\r\\\\nThe results show that different implementation concepts require different measures. From the analysis of the results, the conclusions are that integrated energy planning is more important than ever. Understanding the different dimensions of sustainable development in combination with energy supply and consumption is important to plan and realize settlements that not only contribute significantly to reducing energy consumption and securing the location of energy infrastructure (generation, distribution, storage), but also in terms of long-term sustainable development and specifically climate neutrality. shows/highlight the importance of integrated and cross-sector approaches of PEDs that are implemented and operated in multi-stakeholder settings.

**Comment by phish108** [comment]
I saw double and tripple escaping as well.

**Comment by stlozhaw** [comment]
Looks like this is going on.

1. The abstract field contains `cr` as HTML encoded character `&#xd;`
    - Gets decoded to `\r` by the XML parser
2. The clean_string function replaces `cr`, `lf` and other characters

Example:
`interviews.&#xd;\nThe` =(Parser)> `interviews.\r\nThe` =(clean_string)> `interviews.\\r\\nThe`

The reasoning for why the `clean_string` function is required does not seem to be true and inserts still work without calling it.

https://github.com/sustainability-zhaw/extraction-dspace/blob/b9e749f5e25662b4c1e2426c908f6b845efaab66/src/hookup.py#L111-L137
